name: project_sem2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_gen_runner: ^5.10.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  device_preview: ^1.2.0
  d_method: ^0.2.6
  lottie: ^3.3.1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/success.json

flutter_gen:
  output: lib/core/assets/
  integration:
    flutter_svg: true
